In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

#from linear_regression_salary import X_test, y_test

insure=pd.read_csv("Insure_auto.csv")
X=insure[['Home']]#needs a DF as it requires a 2D else it gives a series
y=insure['Operating_Cost']

Polynomial with Degree=2

In [2]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_poly

    Home    Home^2
0  400.0  160000.0
1  350.0  122500.0
2  600.0  360000.0
3  800.0  640000.0
4  900.0  810000.0
5  200.0   40000.0
6  120.0   14400.0
7  340.0  115600.0
8  490.0  240100.0
9  700.0  490000.0

In [3]:
lr=LinearRegression()
lr.fit(X_poly,y)
lr.coef_, lr.intercept_

(array([57.28485112,  0.15387525]), np.float64(54381.71562081708))

In [4]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_poly

    Home    Home^2
0  400.0  160000.0
1  350.0  122500.0
2  600.0  360000.0
3  800.0  640000.0
4  900.0  810000.0
5  200.0   40000.0
6  120.0   14400.0
7  340.0  115600.0
8  490.0  240100.0
9  700.0  490000.0

In [5]:
insure=pd.read_csv("Insure_auto.csv")
X=insure[['Home','Automobile']]#needs a DF as it requires a 2D else it gives a series
y=insure['Operating_Cost']
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

    Home  Automobile    Home^2  Home Automobile  Automobile^2
0  400.0      1200.0  160000.0         480000.0     1440000.0
1  350.0       360.0  122500.0         126000.0      129600.0
2  600.0       800.0  360000.0         480000.0      640000.0
3  800.0      1800.0  640000.0        1440000.0     3240000.0
4  900.0      1600.0  810000.0        1440000.0     2560000.0
5  200.0      1000.0   40000.0         200000.0     1000000.0
6  120.0       900.0   14400.0         108000.0      810000.0
7  340.0      1100.0  115600.0         374000.0     1210000.0
8  490.0       900.0  240100.0         441000.0      810000.0
9  700.0       800.0  490000.0         560000.0      640000.0

In [6]:
lr.fit(X_poly,y)
lr.coef_, lr.intercept_

(array([ 1.47533405e+02,  5.88905218e+01, -7.94261684e-02,  9.36654775e-02,
        -2.65057986e-02]),
 np.float64(-1455.2310308279848))

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
insure=pd.read_csv("Insure_auto.csv")
X=insure[['Home','Automobile']]#needs a DF as it requires a 2D else it gives a series
y=insure['Operating_Cost']
train_test_split(insure, test_size=0.3)

[  Branch  Home  Automobile  Operating_Cost
 7    B08   340        1100          110000
 2    B03   600         800          136000
 8    B09   490         900          120000
 3    B04   800        1800          219000
 5    B06   200        1000           75000
 9    B10   700         800          144000
 4    B05   900        1600          230000,
   Branch  Home  Automobile  Operating_Cost
 6    B07   120         900           56000
 1    B02   350         360           71000
 0    B01   400        1200          124000]

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y , test_size=0.3, random_state=25)

In [9]:
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mean_absolute_error(y_test,y_pred)

6387.3699150211905

In [10]:
boston=pd.read_csv("Boston.csv")
X=boston.drop('medv',axis=1)
y=boston['medv']
lr=LinearRegression()
X_train,X_test,y_train,y_test=train_test_split(X,y , test_size=0.3, random_state=25)
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mean_absolute_error(y_test,y_pred)

3.1175694194800987

In [11]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y , test_size=0.3, random_state=25)
X_poly.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       ...
       'tax^2', 'tax ptratio', 'tax black', 'tax lstat', 'ptratio^2',
       'ptratio black', 'ptratio lstat', 'black^2', 'black lstat', 'lstat^2'],
      dtype='object', length=104)

In [12]:
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mean_absolute_error(y_test, y_pred)

2.6635485509433483

In [13]:
housing=pd.read_csv("Housing.csv")
dum_hous=pd.get_dummies(housing,drop_first=True)
dum_hous

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,True,True,False,False,True,False
542,94000.0,6000,3,2,4,0,True,False,False,False,True,False
543,103000.0,6000,3,2,4,1,True,True,False,False,True,False
544,105000.0,6000,3,2,2,1,True,True,False,False,True,False
545,105000.0,6000,3,1,2,1,True,False,False,False,True,False

In [14]:
X=dum_hous.drop('price',axis=1)
y=dum_hous['price']
lr = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
mean_absolute_error(y_test, y_pred)

11600.941705536448

In [15]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y , test_size=0.3, random_state=25)
# X_poly.columns
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mean_absolute_error(y_test, y_pred)

12967.811723499355

In [16]:
poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y , test_size=0.3, random_state=25)
# X_poly.columns
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mean_absolute_error(y_test, y_pred)

18546.459691175853