### Bag of Words

In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize
sent1='It is good practice for us.'
sent2='It was also good to know about it.'

In [2]:
tokens=word_tokenize(sent1.lower())+word_tokenize(sent2.lower())

In [3]:
tokens=set(tokens)
tokens

{'.',
 'about',
 'also',
 'for',
 'good',
 'is',
 'it',
 'know',
 'practice',
 'to',
 'us',
 'was'}

In [4]:
df=pd.DataFrame({},index=[1,2],columns=list(tokens))

In [5]:
df

  about   us practice know   to also  was   is   it  for    . good
1   NaN  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [6]:
tokens1=word_tokenize(sent1.lower())
tokens2=word_tokenize(sent2.lower())

In [7]:
count1=[tokens1.count(word) for word in df.columns]
count2=[tokens2.count(word) for word in df.columns]

In [8]:
count1

[0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [9]:
count2

[1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 1]

In [10]:
df.iloc[0]=count1

In [11]:
df.iloc[1]=count2

In [12]:
df

  about us practice know to also was is it for  . good
1     0  1        1    0  0    0   0  1  1   1  1    1
2     1  0        0    1  1    1   1  0  2   0  1    1

In [13]:
df.columns

Index(['about', 'us', 'practice', 'know', 'to', 'also', 'was', 'is', 'it',
       'for', '.', 'good'],
      dtype='object')

### Count Vectorizer

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cvt=CountVectorizer()

In [15]:
new_data=cvt.fit_transform([sent1,sent2])

In [16]:
new_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (2, 11)>

In [17]:
new_data.toarray()

array([[0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1]])

In [18]:
cvt.get_feature_names_out()

array(['about', 'also', 'for', 'good', 'is', 'it', 'know', 'practice',
       'to', 'us', 'was'], dtype=object)

In [19]:
df=pd.DataFrame(new_data.toarray(),columns=cvt.get_feature_names_out())

In [20]:
df

   about  also  for  good  is  it  know  practice  to  us  was
0      0     0    1     1   1   1     0         1   0   1    0
1      1     1    0     1   0   2     1         0   1   0    1

In [21]:
new_sent='It was about good practice.'

In [22]:
#new_data=cvt.fit_transform([sent1,sent2,new_sent])

In [23]:
df=pd.DataFrame(new_data.toarray(),columns=cvt.get_feature_names_out())

In [24]:
df

   about  also  for  good  is  it  know  practice  to  us  was
0      0     0    1     1   1   1     0         1   0   1    0
1      1     1    0     1   0   2     1         0   1   0    1

In [25]:
cvt.transform([new_sent]).toarray()

array([[1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1]])

### N-gram vectorization

In [39]:
sent1='It is good practice for us.'
sent2='It was also good to know about it.'

In [40]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(
 |      *,
 |      input='content',
 |      encoding='utf-8',
 |      decode_error='strict',
 |      strip_accents=None,
 |      lowercase=True,
 |      preprocessor=None,
 |      tokenizer=None,
 |      stop_words=None,
 |      token_pattern='(?u)\\b\\w\\w+\\b',
 |      ngram_range=(1, 1),
 |      analyzer='word',
 |      max_df=1.0,
 |      min_df=1,
 |      max_features=None,
 |      vocabulary=None,
 |      binary=False,
 |      dtype=<class 'numpy.int64'>
 |  )
 |
 |  Convert a collection of text documents to a matrix of token counts.
 |
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.
 |
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |
 |  Parameters
 |  ----------
 |  input : {'filename', 'file', 'content'}, default='content'
 |      - If `'filename'`, the sequence passed as an argument to fit is
 |        expected to be a list of filenames that need reading to fetch
 |        the raw content to analyze.
 |
 |      - If `'file'`, the sequence items must have a 'read' method (file-like
 |        object) that is called to fetch the bytes in memory.
 |
 |      - If `'content'`, the input is expected to be a sequence of items that
 |        can be of type string or byte.
 |
 |  encoding : str, default='utf-8'
 |      If bytes or files are given to analyze, this encoding is used to
 |      decode.
 |
 |  decode_error : {'strict', 'ignore', 'replace'}, default='strict'
 |      Instruction on what to do if a byte sequence is given to analyze that
 |      contains characters not of the given `encoding`. By default, it is
 |      'strict', meaning that a UnicodeDecodeError will be raised. Other
 |      values are 'ignore' and 'replace'.
 |
 |  strip_accents : {'ascii', 'unicode'} or callable, default=None
 |      Remove accents and perform other character normalization
 |      during the preprocessing step.
 |      'ascii' is a fast method that only works on characters that have
 |      a direct ASCII mapping.
 |      'unicode' is a slightly slower method that works on any characters.
 |      None (default) means no character normalization is performed.
 |
 |      Both 'ascii' and 'unicode' use NFKD normalization from
 |      :func:`unicodedata.normalize`.
 |
 |  lowercase : bool, default=True
 |      Convert all characters to lowercase before tokenizing.
 |
 |  preprocessor : callable, default=None
 |      Override the preprocessing (strip_accents and lowercase) stage while
 |      preserving the tokenizing and n-grams generation steps.
 |      Only applies if ``analyzer`` is not callable.
 |
 |  tokenizer : callable, default=None
 |      Override the string tokenization step while preserving the
 |      preprocessing and n-grams generation steps.
 |      Only applies if ``analyzer == 'word'``.
 |
 |  stop_words : {'english'}, list, default=None
 |      If 'english', a built-in stop word list for English is used.
 |      There are several known issues with 'english' and you should
 |      consider an alternative (see :ref:`stop_words`).
 |
 |      If a list, that list is assumed to contain stop words, all of which
 |      will be removed from the resulting tokens.
 |      Only applies if ``analyzer == 'word'``.
 |
 |      If None, no stop words will be used. In this case, setting `max_df`
 |      to a higher value, such as in the range (0.7, 1.0), can automatically detect
 |      and filter stop words based on intra corpus document frequency of terms.
 |
 |  token_pattern : str or None, default=r"(?u)\\b\\w\\w+\\b"
 |      Regular expression denoting what constitutes a "token", only used
 |      if ``analyzer == 'word'``. The default regexp select tokens of 2
 |      or more alphanumeric characters (punctuation is completely ignored
 |      and always treated as a token separator).
 |
 |      If there is a capturing group in token_pattern then the
 |      captured group content, not the entire match, becomes the token.
 |      At most one capturing group is permitted.
 |
 |  ngram_range : tuple (min_n, max_n), default=(1, 1)
 |      The lower and upper boundary of the range of n-values for different
 |      word n-grams or char n-grams to be extracted. All values of n such
 |      such that min_n <= n <= max_n will be used. For example an
 |      ``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` means
 |      unigrams and bigrams, and ``(2, 2)`` means only bigrams.
 |      Only applies if ``analyzer`` is not callable.
 |
 |  analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
 |      Whether the feature should be made of word n-gram or character
 |      n-grams.
 |      Option 'char_wb' creates character n-grams only from text inside
 |      word boundaries; n-grams at the edges of words are padded with space.
 |
 |      If a callable is passed it is used to extract the sequence of features
 |      out of the raw, unprocessed input.
 |
 |      .. versionchanged:: 0.21
 |
 |      Since v0.21, if ``input`` is ``filename`` or ``file``, the data is
 |      first read from the file and then passed to the given callable
 |      analyzer.
 |
 |  max_df : float in range [0.0, 1.0] or int, default=1.0
 |      When building the vocabulary ignore terms that have a document
 |      frequency strictly higher than the given threshold (corpus-specific
 |      stop words).
 |      If float, the parameter represents a proportion of documents, integer
 |      absolute counts.
 |      This parameter is ignored if vocabulary is not None.
 |
 |  min_df : float in range [0.0, 1.0] or int, default=1
 |      When building the vocabulary ignore terms that have a document
 |      frequency strictly lower than the given threshold. This value is also
 |      called cut-off in the literature.
 |      If float, the parameter represents a proportion of documents, integer
 |      absolute counts.
 |      This parameter is ignored if vocabulary is not None.
 |
 |  max_features : int, default=None
 |      If not None, build a vocabulary that only consider the top
 |      `max_features` ordered by term frequency across the corpus.
 |      Otherwise, all features are used.
 |
 |      This parameter is ignored if vocabulary is not None.
 |
 |  vocabulary : Mapping or iterable, default=None
 |      Either a Mapping (e.g., a dict) where keys are terms and values are
 |      indices in the feature matrix, or an iterable over terms. If not
 |      given, a vocabulary is determined from the input documents. Indices
 |      in the mapping should not be repeated and should not have any gap
 |      between 0 and the largest index.
 |
 |  binary : bool, default=False
 |      If True, all non zero counts are set to 1. This is useful for discrete
 |      probabilistic models that model binary events rather than integer
 |      counts.
 |
 |  dtype : dtype, default=np.int64
 |      Type of the matrix returned by fit_transform() or transform().
 |
 |  Attributes
 |  ----------
 |  vocabulary_ : dict
 |      A mapping of terms to feature indices.
 |
 |  fixed_vocabulary_ : bool
 |      True if a fixed vocabulary of term to indices mapping
 |      is provided by the user.
 |
 |  See Also
 |  --------
 |  HashingVectorizer : Convert a collection of text documents to a
 |      matrix of token counts.
 |
 |  TfidfVectorizer : Convert a collection of raw documents to a matrix
 |      of TF-IDF features.
 |
 |  Examples
 |  --------
 |  >>> from sklearn.feature_extraction.text import CountVectorizer
 |  >>> corpus = [
 |  ...     'This is the first document.',
 |  ...     'This document is the second document.',
 |  ...     'And this is the third one.',
 |  ...     'Is this the first document?',
 |  ... ]
 |  >>> vectorizer = CountVectorizer()
 |  >>> X = vectorizer.fit_transform(corpus)
 |  >>> vectorizer.get_feature_names_out()
 |  array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
 |         'this'], ...)
 |  >>> print(X.toarray())
 |  [[0 1 1 1 0 0 1 0 1]
 |   [0 2 0 1 0 1 1 0 1]
 |   [1 0 0 1 1 0 1 1 1]
 |   [0 1 1 1 0 0 1 0 1]]
 |  >>> vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
 |  >>> X2 = vectorizer2.fit_transform(corpus)
 |  >>> vectorizer2.get_feature_names_out()
 |  array(['and this', 'document is', 'first document', 'is the', 'is this',
 |         'second document', 'the first', 'the second', 'the third', 'third one',
 |         'this document', 'this is', 'this the'], ...)
 |   >>> print(X2.toarray())
 |   [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 |   [0 1 0 1 0 1 0 1 0 0 1 0 0]
 |   [1 0 0 1 0 0 0 0 1 1 0 1 0]
 |   [0 0 1 0 1 0 1 0 0 0 0 0 1]]
 |
 |  Method resolution order:
 |      CountVectorizer
 |      _VectorizerMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(
 |      self,
 |      *,
 |      input='content',
 |      encoding='utf-8',
 |      decode_error='strict',
 |      strip_accents=None,
 |      lowercase=True,
 |      preprocessor=None,
 |      tokenizer=None,
 |      stop_words=None,
 |      token_pattern='(?u)\\b\\w\\w+\\b',
 |      ngram_range=(1, 1),
 |      analyzer='word',
 |      max_df=1.0,
 |      min_df=1,
 |      max_features=None,
 |      vocabulary=None,
 |      binary=False,
 |      dtype=<class 'numpy.int64'>
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __sklearn_tags__(self)
 |
 |  fit(self, raw_documents, y=None)
 |      Learn a vocabulary dictionary of all tokens in the raw documents.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      y : None
 |          This parameter is ignored.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted vectorizer.
 |
 |  fit_transform(self, raw_documents, y=None)
 |      Learn the vocabulary dictionary and return document-term matrix.
 |
 |      This is equivalent to fit followed by transform, but more efficiently
 |      implemented.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      y : None
 |          This parameter is ignored.
 |
 |      Returns
 |      -------
 |      X : array of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |  get_feature_names_out(self, input_features=None)
 |      Get output feature names for transformation.
 |
 |      Parameters
 |      ----------
 |      input_features : array-like of str or None, default=None
 |          Not used, present here for API consistency by convention.
 |
 |      Returns
 |      -------
 |      feature_names_out : ndarray of str objects
 |          Transformed feature names.
 |
 |  inverse_transform(self, X)
 |      Return terms per document with nonzero entries in X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |      Returns
 |      -------
 |      X_original : list of arrays of shape (n_samples,)
 |          List of arrays of terms.
 |
 |  transform(self, raw_documents)
 |      Transform documents to document-term matrix.
 |
 |      Extract token counts out of raw text documents using the vocabulary
 |      fitted with fit or the one provided to the constructor.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      Returns
 |      -------
 |      X : sparse matrix of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _VectorizerMixin:
 |
 |  build_analyzer(self)
 |      Return a callable to process input data.
 |
 |      The callable handles preprocessing, tokenization, and n-grams generation.
 |
 |      Returns
 |      -------
 |      analyzer: callable
 |          A function to handle preprocessing, tokenization
 |          and n-grams generation.
 |
 |  build_preprocessor(self)
 |      Return a function to preprocess the text before tokenization.
 |
 |      Returns
 |      -------
 |      preprocessor: callable
 |            A function to preprocess the text before tokenization.
 |
 |  build_tokenizer(self)
 |      Return a function that splits a string into a sequence of tokens.
 |
 |      Returns
 |      -------
 |      tokenizer: callable
 |            A function to split a string into a sequence of tokens.
 |
 |  decode(self, doc)
 |      Decode the input into a string of unicode symbols.
 |
 |      The decoding strategy depends on the vectorizer parameters.
 |
 |      Parameters
 |      ----------
 |      doc : bytes or str
 |          The string to decode.
 |
 |      Returns
 |      -------
 |      doc: str
 |          A string of unicode symbols.
 |
 |  get_stop_words(self)
 |      Build or fetch the effective stop words list.
 |
 |      Returns
 |      -------
 |      stop_words: list or None
 |              A list of stop words.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from _VectorizerMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  get_metadata_routing(self)
 |      Get metadata routing of this object.
 |
 |      Please check :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      Returns
 |      -------
 |      routing : MetadataRequest
 |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
 |          routing information.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  __init_subclass__(**kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487

In [41]:
ngram_cvt=CountVectorizer(ngram_range=(2,2))

In [42]:
new_data=ngram_cvt.fit_transform([sent1,sent2])

In [43]:
ngram_cvt.get_feature_names_out()

array(['about it', 'also good', 'for us', 'good practice', 'good to',
       'is good', 'it is', 'it was', 'know about', 'practice for',
       'to know', 'was also'], dtype=object)

In [44]:
df=pd.DataFrame(new_data.toarray(),columns=ngram_cvt.get_feature_names_out())
df

,about it,also good,for us,good practice,good to,is good,it is,it was,know about,practice for,to know,was also
0,0,0,1,1,0,1,1,0,0,1,0,0
1,1,1,0,0,1,0,0,1,1,0,1,1