In [12]:
import pandas as pd
from numpy.conftest import dtype

# Boolean Indexing
dataset=pd.read_csv('tips.csv')
filtered1=dataset[(dataset['gender']=='Female') & (dataset['tip']>=4)]
filtered1

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.181240e+15,Fri6963
104,20.92,4.08,Female,No,Sat,Dinner,2,10.46,Gabrielle Frederick,4.013010e+15,Sat3194
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,3.756390e+14,Sat2614
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400160e+15,Sun6492
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.038570e+11,Thur3948
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4.311050e+12,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210880e+15,Sun9176
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4.211810e+12,Sun4598
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4.317020e+15,Thur967
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.544900e+15,Thur9313
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.922300e+15,Sat3374
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,6.761840e+11,Sat9777

In [11]:
#Using Query
filtered2=dataset.query('gender=="Female" and tip>=4')
filtered2

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.181240e+15,Fri6963
104,20.92,4.08,Female,No,Sat,Dinner,2,10.46,Gabrielle Frederick,4.013010e+15,Sat3194
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,3.756390e+14,Sat2614
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400160e+15,Sun6492
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.038570e+11,Thur3948
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4.311050e+12,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210880e+15,Sun9176
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4.211810e+12,Sun4598
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4.317020e+15,Thur967
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.544900e+15,Thur9313
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.922300e+15,Sat3374
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,6.761840e+11,Sat9777

In [10]:
#Using loc with conditions
filtered3=dataset.loc[(dataset['gender']=='Female') & (dataset['tip']>=4)]
filtered3

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.181240e+15,Fri6963
104,20.92,4.08,Female,No,Sat,Dinner,2,10.46,Gabrielle Frederick,4.013010e+15,Sat3194
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,3.756390e+14,Sat2614
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400160e+15,Sun6492
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.038570e+11,Thur3948
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4.311050e+12,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210880e+15,Sun9176
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4.211810e+12,Sun4598
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4.317020e+15,Thur967
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.544900e+15,Thur9313
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.922300e+15,Sat3374
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,6.761840e+11,Sat9777

In [9]:
#Using where(return NaN where condition is False)
filtered4=dataset.where((dataset['gender']=='Female') & (dataset['tip']>=4))
filtered4=filtered4.dropna()
filtered4

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4.0,8.82,Diane Macias,4.577820e+15,Sun6686
52,34.81,5.20,Female,No,Sun,Dinner,4.0,8.70,Emily Daniel,4.291280e+15,Sun6165
73,25.28,5.00,Female,Yes,Sat,Dinner,2.0,12.64,Julie Holmes,5.418690e+15,Sat6065
85,34.83,5.17,Female,No,Thur,Lunch,4.0,8.71,Shawna Cook,6.011790e+15,Thur7972
93,16.32,4.30,Female,Yes,Fri,Dinner,2.0,8.16,Natalie Nguyen,5.181240e+15,Fri6963
104,20.92,4.08,Female,No,Sat,Dinner,2.0,10.46,Gabrielle Frederick,4.013010e+15,Sat3194
109,14.31,4.00,Female,Yes,Sat,Dinner,2.0,7.16,Amanda Anderson,3.756390e+14,Sat2614
114,25.71,4.00,Female,No,Sun,Dinner,3.0,8.57,Katie Smith,5.400160e+15,Sun6492
125,29.80,4.20,Female,No,Thur,Lunch,6.0,4.97,Angela Sanchez,5.038570e+11,Thur3948
143,27.05,5.00,Female,No,Thur,Lunch,6.0,4.51,Regina Jones,4.311050e+12,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5.0,5.97,Madison Wilson,4.210880e+15,Sun9176
178,9.60,4.00,Female,Yes,Sun,Dinner,2.0,4.80,Melanie Gray,4.211810e+12,Sun4598
191,19.81,4.19,Female,Yes,Thur,Lunch,2.0,9.90,Kristy Boyd,4.317020e+15,Thur967
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,10.78,Brooke Soto,5.544900e+15,Thur9313
214,28.17,6.50,Female,Yes,Sat,Dinner,3.0,9.39,Marissa Jackson,4.922300e+15,Sat3374
238,35.83,4.67,Female,No,Sat,Dinner,3.0,11.94,Kimberly Crane,6.761840e+11,Sat9777

In [25]:
import numpy as np
np.random.seed(42)
scores=np.random.randint(0,101,(4,3))
players=['virat','rohit','ms dhoni','k l rahul']
matches=['match1','match2','match3']
df=pd.DataFrame(data=scores,index=players,columns=matches)
print(df)
print(df.info())
print(df.loc['virat'])
print(df.loc[['virat','rohit']])
print(df.loc['virat','match2'])

           match1  match2  match3
virat          51      92      14
rohit          71      60      20
ms dhoni       82      86      74
k l rahul      74      87      99
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, virat to k l rahul
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   match1  4 non-null      int32
 1   match2  4 non-null      int32
 2   match3  4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes
None
match1    51
match2    92
match3    14
Name: virat, dtype: int32
       match1  match2  match3
virat      51      92      14
rohit      71      60      20
92

In [24]:
print(df.iloc[0])
print(df.iloc[0:2])
print(df.iloc[0,1])

match1    51
match2    92
match3    14
Name: virat, dtype: int32
       match1  match2  match3
virat      51      92      14
rohit      71      60      20
92

In [28]:
students=np.array([
    ('Alice',95,20),
    ('Bob',88,21),
    ('Charlie',92,19),
],dtype=[('name','U10'),('marks','i4'),('age','i4')])
print(students)

[('Alice', 95, 20) ('Bob', 88, 21) ('Charlie', 92, 19)]

In [39]:
df=dataset.copy()
df_grouped=df.groupby('gender')
print(df_grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002E523E1BE50>

In [37]:
mean_tip=df_grouped['tip'].mean()
print(mean_tip)

gender
Female    2.833448
Male      3.089618
Name: tip, dtype: float64

In [45]:
df_grouped_day=df.groupby(['gender','day'])
mean_tip_by_gender=df_grouped_day['tip'].mean()
print(mean_tip_by_gender)

gender  day
Female  Fri     2.781111
        Sat     2.801786
        Sun     3.367222
        Thur    2.575625
Male    Fri     2.693000
        Sat     3.083898
        Sun     3.220345
        Thur    2.980333
Name: tip, dtype: float64

In [50]:
df_grouped_agg=df.groupby(['gender','day']).agg({'tip':['mean','sum','min','max']}).reset_index()
print(df_grouped_agg)

   gender   day       tip
                     mean     sum   min    max
0  Female   Fri  2.781111   25.03  1.00   4.30
1  Female   Sat  2.801786   78.45  1.00   6.50
2  Female   Sun  3.367222   60.61  1.01   5.20
3  Female  Thur  2.575625   82.42  1.25   5.17
4    Male   Fri  2.693000   26.93  1.50   4.73
5    Male   Sat  3.083898  181.95  1.00  10.00
6    Male   Sun  3.220345  186.78  1.32   6.50
7    Male  Thur  2.980333   89.41  1.44   6.70

In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('MS_Dhoni_ODI_record.csv')
print(df.head())
print(df.tail())

  score runs_scored balls_faced strike_rate fours sixes    opposition  \
0     0           0           1           0     0     0  v Bangladesh
1    12          12          11      109.09     2     0  v Bangladesh
2    7*           7           2         350     0     1  v Bangladesh
3     3           3           7       42.85     0     0    v Pakistan
4   148         148         123      120.32    15     4    v Pakistan

          ground        date  odi_number
0     Chattogram  23/12/2004  ODI # 2199
1          Dhaka  26/12/2004  ODI # 2201
2          Dhaka  27/12/2004  ODI # 2202
3          Kochi  02/04/2005  ODI # 2235
4  Visakhapatnam  05/04/2005  ODI # 2236
    score runs_scored balls_faced strike_rate fours sixes     opposition  \
345   56*          56          61        91.8     3     2  v West Indies
346   42*          42          31      135.48     4     1      v England
347    35          35          33      106.06     4     0   v Bangladesh
348   DNB           -           -           -     -     -    v Sri Lanka
349    50          50          72       69.44     1     1  v New Zealand

         ground        date  odi_number
345  Manchester  27/06/2019  ODI # 4175
346  Birmingham  30/06/2019  ODI # 4179
347  Birmingham  02/07/2019  ODI # 4182
348       Leeds  06/07/2019  ODI # 4187
349  Manchester  09/07/2019  ODI # 4190

In [93]:
df['opposition']=df['opposition'].apply(lambda x: x[2:])
#df['opposition']=df['opposition'].str.replace('v ','',regex=False)
print(df['opposition'].head())

0    Bangladesh
1    Bangladesh
2    Bangladesh
3      Pakistan
4      Pakistan
Name: opposition, dtype: object

In [94]:
df['date']=pd.to_datetime(df['date'],dayfirst=True)#dayfirst used to change date format in the date section
df['year']=df['date'].dt.year.astype(int)
print(df.head())

  score runs_scored balls_faced strike_rate fours sixes  opposition  \
0     0           0           1           0     0     0  Bangladesh
1    12          12          11      109.09     2     0  Bangladesh
2    7*           7           2         350     0     1  Bangladesh
3     3           3           7       42.85     0     0    Pakistan
4   148         148         123      120.32    15     4    Pakistan

          ground       date  odi_number  year
0     Chattogram 2004-12-23  ODI # 2199  2004
1          Dhaka 2004-12-26  ODI # 2201  2004
2          Dhaka 2004-12-27  ODI # 2202  2004
3          Kochi 2005-04-02  ODI # 2235  2005
4  Visakhapatnam 2005-04-05  ODI # 2236  2005

In [95]:
df['score']=df['score'].apply(str)
df['not out']=np.where(df['score'].str.endswith('*'),1,0)#check not out using * and assign with 1 or 0
print(df.head())

  score runs_scored balls_faced strike_rate fours sixes  opposition  \
0     0           0           1           0     0     0  Bangladesh
1    12          12          11      109.09     2     0  Bangladesh
2    7*           7           2         350     0     1  Bangladesh
3     3           3           7       42.85     0     0    Pakistan
4   148         148         123      120.32    15     4    Pakistan

          ground       date  odi_number  year  not out
0     Chattogram 2004-12-23  ODI # 2199  2004        0
1          Dhaka 2004-12-26  ODI # 2201  2004        0
2          Dhaka 2004-12-27  ODI # 2202  2004        1
3          Kochi 2005-04-02  ODI # 2235  2005        0
4  Visakhapatnam 2005-04-05  ODI # 2236  2005        0

In [96]:
df.drop(columns='odi_number',inplace=True)#makes change to original dataframe using inplace
print(df.head())

  score runs_scored balls_faced strike_rate fours sixes  opposition  \
0     0           0           1           0     0     0  Bangladesh
1    12          12          11      109.09     2     0  Bangladesh
2    7*           7           2         350     0     1  Bangladesh
3     3           3           7       42.85     0     0    Pakistan
4   148         148         123      120.32    15     4    Pakistan

          ground       date  year  not out
0     Chattogram 2004-12-23  2004        0
1          Dhaka 2004-12-26  2004        0
2          Dhaka 2004-12-27  2004        1
3          Kochi 2005-04-02  2005        0
4  Visakhapatnam 2005-04-05  2005        0

In [97]:
df_new=df.loc[((df['score']!='DNB') & (df['score']!='TDNB')),'runs_scored':]
print(df_new.head())

  runs_scored balls_faced strike_rate fours sixes  opposition         ground  \
0           0           1           0     0     0  Bangladesh     Chattogram
1          12          11      109.09     2     0  Bangladesh          Dhaka
2           7           2         350     0     1  Bangladesh          Dhaka
3           3           7       42.85     0     0    Pakistan          Kochi
4         148         123      120.32    15     4    Pakistan  Visakhapatnam

        date  year  not out
0 2004-12-23  2004        0
1 2004-12-26  2004        0
2 2004-12-27  2004        1
3 2005-04-02  2005        0
4 2005-04-05  2005        0

In [99]:
df_new['runs_scored']=df_new['runs_scored'].astype(int)
df_new['balls_faced']=df_new['balls_faced'].astype(int)
df_new['strike_rate']=df_new['strike_rate'].astype(float)
df['fours']=df_new['fours'].astype(int)
df_new['sixes']=df_new['sixes'].astype(int)
print(df_new.head())

   runs_scored  balls_faced  strike_rate fours  sixes  opposition  \
0            0            1         0.00     0      0  Bangladesh
1           12           11       109.09     2      0  Bangladesh
2            7            2       350.00     0      1  Bangladesh
3            3            7        42.85     0      0    Pakistan
4          148          123       120.32    15      4    Pakistan

          ground       date  year  not out
0     Chattogram 2004-12-23  2004        0
1          Dhaka 2004-12-26  2004        0
2          Dhaka 2004-12-27  2004        1
3          Kochi 2005-04-02  2005        0
4  Visakhapatnam 2005-04-05  2005        0