In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.compose import make_column_transformer, make_column_selector
import warnings;

warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler, OneHotEncoder

In [2]:
hr = pd.read_csv('HR_comma_sep.csv')
hr_tst = pd.read_csv('../Logistic_reg/tst_hr.csv')

In [8]:
X = hr.drop(["left"], axis=1)
y = hr["left"]
cat_cols = list(X.columns[X.dtypes == "object"])
num_cols = list(X.columns[X.dtypes != "object"])

In [5]:
def knn(X, y):
    # Encode categorical columns
    X = X.copy()
    for col in X.select_dtypes(include='object').columns:
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsRegressor(n_neighbors=n)
        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        scores.append([r2_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["r2_score", "n"])
    scores = scores.sort_values("r2_score", ascending=False)
    return scores

knn(X, y)

   r2_score   n
1  0.762682   2
0  0.759356   1
2  0.744711   3
3  0.731090   4
4  0.720321   5
5  0.715991   6
6  0.715206   7
7  0.714803   8
8  0.711479   9
9  0.706886  10

In [6]:
def knn_scl(X, y, ss):
    # Encode categorical columns
    X = X.copy()
    for col in X.select_dtypes(include='object').columns:
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25) #Stratify is for classification and not for regression.
    X_trn_ss = ss.fit_transform(X_train)
    X_tst_ss = ss.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsRegressor(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([r2_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["r2_score", "n"])
    scores = scores.sort_values("r2_score", ascending=False)
    return scores

ss = StandardScaler()
knn_scl(X, y, ss)

   r2_score   n
0  0.840377   1
1  0.832819   2
2  0.820491   3
4  0.813580   5
3  0.812715   4
5  0.811556   6
6  0.810121   7
7  0.807784   8
8  0.804995   9
9  0.800459  10

In [7]:
def knn_scl(X, y, ss):
    # Encode categorical columns
    X = X.copy()
    for col in X.select_dtypes(include='object').columns:
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25) #Stratify is for classification and not for regression.
    X_trn_ss = ss.fit_transform(X_train)
    X_tst_ss = ss.transform(X_test)
    scores = []
    for n in range(1, 11):
        knn = KNeighborsRegressor(n_neighbors=n)
        knn.fit(X_trn_ss, y_train)
        y_pred = knn.predict(X_tst_ss)
        scores.append([r2_score(y_test, y_pred), n])

    scores = pd.DataFrame(scores, columns=["r2_score", "n"])
    scores = scores.sort_values("r2_score", ascending=False)
    return scores

ss = MinMaxScaler()
knn_scl(X, y, ss)

   r2_score   n
0  0.825866   1
1  0.817401   2
2  0.805712   3
5  0.801983   6
3  0.801756   4
4  0.801536   5
6  0.799114   7
7  0.797864   8
8  0.793708   9
9  0.790168  10

In [13]:
ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
trns = make_column_transformer((ohe, cat_cols), remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')
X_trns = trns.fit_transform(X)
X_trns

,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_low,salary_medium,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.38,0.53,2,157,3,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.80,0.86,5,262,6,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.10,0.77,6,247,4,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.92,0.85,5,259,5,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.89,1.00,5,224,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.40,0.57,2,151,3,0,0
14991,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.48,2,160,3,0,0
14992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.53,2,143,3,0,0
14993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.11,0.96,6,280,4,0,0
14994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.52,2,158,3,0,0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_trns, y, test_size=0.3, random_state=25)

In [22]:
ss = StandardScaler().set_output(transform='pandas')
knn = KNeighborsRegressor(n_neighbors=1)
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)
knn.fit(X_train_scaled, y_train)

KNeighborsRegressor(n_neighbors=1)

In [23]:
y_pred = knn.predict(X_test_scaled)
tst = pd.read_csv("../Logistic_reg/tst_hr.csv")
tst_trns = trns.transform(tst)
tst_scl = ss.transform(tst_trns)
print(knn.predict(tst_scl))

[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [24]:
r2_score(y_test, y_pred)

0.7956343382671531

In [27]:
#Without the use of cat_cols and num_cols and using make_column_selector instead:

ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
trns = make_column_transformer((ohe, make_column_selector(dtype_include=object)), remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')
X_trns = trns.fit_transform(X)
X_trns

,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_low,salary_medium,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.38,0.53,2,157,3,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.80,0.86,5,262,6,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.10,0.77,6,247,4,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.92,0.85,5,259,5,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.89,1.00,5,224,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.40,0.57,2,151,3,0,0
14991,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.48,2,160,3,0,0
14992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.53,2,143,3,0,0
14993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.11,0.96,6,280,4,0,0
14994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.37,0.52,2,158,3,0,0

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X_trns, y, test_size=0.3, random_state=25)
ss = StandardScaler().set_output(transform='pandas')
knn = KNeighborsRegressor(n_neighbors=1)
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)
knn.fit(X_train_scaled, y_train)

KNeighborsRegressor(n_neighbors=1)

In [29]:
y_pred = knn.predict(X_test_scaled)
tst = pd.read_csv("../Logistic_reg/tst_hr.csv")
tst_trns = trns.transform(tst)
tst_scl = ss.transform(tst_trns)
print(knn.predict(tst_scl))

[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [30]:
r2_score(y_test, y_pred)

0.7956343382671531