In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import make_column_transformer,make_column_selector
from sklearn.metrics import classification_report,f1_score
import warnings; warnings.filterwarnings('ignore')

In [2]:
kyph=pd.read_csv('Kyphosis.csv')
y=kyph['Kyphosis']
x=kyph.drop('Kyphosis',axis=1)

In [3]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25,stratify=y)

In [4]:
svm=SVC(kernel='linear',C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print(classification_report(y_test,y_pred))
print(f1_score(y_test,y_pred,pos_label='present'))

              precision    recall  f1-score   support

      absent       0.87      1.00      0.93        20
     present       1.00      0.40      0.57         5

    accuracy                           0.88        25
   macro avg       0.93      0.70      0.75        25
weighted avg       0.90      0.88      0.86        25

0.5714285714285714

In [5]:
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm = SVC(kernel='linear', C=1)
    svm.fit(x_train, y_train)
    y_pred = svm.predict(x_test)
    scores.append([c,f1_score(y_test,y_pred,pos_label='present')])

df_scores=pd.DataFrame(scores,columns=['C','score'])
df_scores.sort_values('score',ascending=False)

           C     score
0   0.001000  0.571429
1   0.264105  0.571429
2   0.527211  0.571429
3   0.790316  0.571429
4   1.053421  0.571429
5   1.316526  0.571429
6   1.579632  0.571429
7   1.842737  0.571429
8   2.105842  0.571429
9   2.368947  0.571429
10  2.632053  0.571429
11  2.895158  0.571429
12  3.158263  0.571429
13  3.421368  0.571429
14  3.684474  0.571429
15  3.947579  0.571429
16  4.210684  0.571429
17  4.473789  0.571429
18  4.736895  0.571429
19  5.000000  0.571429

In [6]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm = SVC(kernel='linear', C=1)
    svm.fit(x_train, y_train)
    y_pred = svm.predict(x_test)
    scores.append([c,f1_score(y_test,y_pred,pos_label='present')])

df_scores=pd.DataFrame(scores,columns=['C','score'])
df_scores.sort_values('score',ascending=False)

           C  score
0   0.001000    0.5
1   0.264105    0.5
2   0.527211    0.5
3   0.790316    0.5
4   1.053421    0.5
5   1.316526    0.5
6   1.579632    0.5
7   1.842737    0.5
8   2.105842    0.5
9   2.368947    0.5
10  2.632053    0.5
11  2.895158    0.5
12  3.158263    0.5
13  3.421368    0.5
14  3.684474    0.5
15  3.947579    0.5
16  4.210684    0.5
17  4.473789    0.5
18  4.736895    0.5
19  5.000000    0.5

In [7]:
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm = SVC(kernel='linear', C=1)
    svm.fit(x_train, y_train)
    y_pred = svm.predict(x_test)
    scores.append([c,f1_score(y_test,y_pred,pos_label='present')])

df_scores=pd.DataFrame(scores,columns=['C','score'])
df_scores.sort_values('score',ascending=False)

           C  score
0   0.001000    0.5
1   0.264105    0.5
2   0.527211    0.5
3   0.790316    0.5
4   1.053421    0.5
5   1.316526    0.5
6   1.579632    0.5
7   1.842737    0.5
8   2.105842    0.5
9   2.368947    0.5
10  2.632053    0.5
11  2.895158    0.5
12  3.158263    0.5
13  3.421368    0.5
14  3.684474    0.5
15  3.947579    0.5
16  4.210684    0.5
17  4.473789    0.5
18  4.736895    0.5
19  5.000000    0.5

In [ ]:
canc=pd.read_csv('BreastCancer.csv')
y=canc['Class']
x=canc.drop('Class',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25,stratify=y)
svm=SVC(kernel='linear',C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print(classification_report(y_test,y_pred))
print(f1_score(y_test,y_pred,pos_label='Malignant'))