In [1]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler, LabelEncoder
from sklearn.compose import make_column_transformer,make_column_selector
from sklearn.metrics import classification_report, f1_score, accuracy_score
import warnings; warnings.filterwarnings('ignore')
from tqdm import tqdm

In [2]:
bcanc=pd.read_csv('BreastCancer.csv')

In [3]:
y=bcanc['Class']
x=bcanc.drop('Class',axis=1)

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25,stratify=y)
svm=SVC(kernel='linear',C=1,max_iter=10000)

In [5]:
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print(classification_report(y_test,y_pred))
print(f1_score(y_test,y_pred,pos_label='Malignant'))

              precision    recall  f1-score   support

      Benign       0.66      0.99      0.79       138
   Malignant       0.00      0.00      0.00        72

    accuracy                           0.65       210
   macro avg       0.33      0.50      0.39       210
weighted avg       0.43      0.65      0.52       210

0.0

In [6]:
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    for g in Gs:
        svm=SVC(kernel='rbf',C=c,gamma=g)
        svm.fit(x_train,y_train)
        y_pred=svm.predict(x_test)
        scores.append([c,g,f1_score(y_test,y_pred,pos_label='Malignant')])
df_scores=pd.DataFrame(scores,columns=['C','Gamma','Score'])
df_scores.sort_values('Score',ascending=False)

            C     Gamma     Score
60   0.790316  0.001000  0.053333
80   1.053421  0.001000  0.051282
180  2.368947  0.001000  0.050000
120  1.579632  0.001000  0.050000
100  1.316526  0.001000  0.050000
..        ...       ...       ...
4    0.001000  1.053421  0.000000
3    0.001000  0.790316  0.000000
2    0.001000  0.527211  0.000000
1    0.001000  0.264105  0.000000
0    0.001000  0.001000  0.000000

[400 rows x 3 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)
svm = SVC(kernel='poly', C=1, max_iter=10000, degree=4)
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)
print(classification_report(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label='Malignant'))

              precision    recall  f1-score   support

      Benign       0.66      1.00      0.79       138
   Malignant       0.00      0.00      0.00        72

    accuracy                           0.66       210
   macro avg       0.33      0.50      0.40       210
weighted avg       0.43      0.66      0.52       210

0.0

## Radial Kernel/ Radial Basis Funtion

In [8]:
#######

## SVM One-Vs-One Classification

In [9]:
glass=pd.read_csv('Glass.csv')
y=glass['Type']
x=glass.drop('Type',axis=1)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)

In [11]:
svm = SVC(kernel='linear', C=1,decision_function_shape='ovo')
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)
print(classification_report(y_test, y_pred))

                                      precision    recall  f1-score   support

    building_windows_float_processed       0.64      0.76      0.70        21
building_windows_non_float_processed       0.61      0.74      0.67        23
                          containers       0.40      0.50      0.44         4
                           headlamps       1.00      0.67      0.80         9
                           tableware       1.00      0.33      0.50         3
     vehicle_windows_float_processed       0.00      0.00      0.00         5

                            accuracy                           0.65        65
                           macro avg       0.61      0.50      0.52        65
                        weighted avg       0.63      0.65      0.62        65

In [12]:
svm = SVC(kernel='linear', C=1,decision_function_shape='ovr')
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)
print(classification_report(y_test, y_pred))

                                      precision    recall  f1-score   support

    building_windows_float_processed       0.64      0.76      0.70        21
building_windows_non_float_processed       0.61      0.74      0.67        23
                          containers       0.40      0.50      0.44         4
                           headlamps       1.00      0.67      0.80         9
                           tableware       1.00      0.33      0.50         3
     vehicle_windows_float_processed       0.00      0.00      0.00         5

                            accuracy                           0.65        65
                           macro avg       0.61      0.50      0.52        65
                        weighted avg       0.63      0.65      0.62        65

In [13]:
svm.decision_function(x_test)

array([[ 5.29278099,  4.298937  , -0.30691158,  0.70802884,  2.05800162,
         3.23952419],
       [ 4.28119527,  5.29363161, -0.2903951 ,  1.75633485,  0.71970439,
         3.22133033],
       [ 4.2910082 ,  5.29030707, -0.28456425,  1.73206112,  0.71357976,
         3.23571882],
       [ 4.2891609 ,  5.29108752,  0.72330663,  0.72457003,  0.71643957,
         3.21848647],
       [ 4.2883828 ,  5.29054543, -0.29497612,  1.75351267,  0.722913  ,
         3.2307326 ],
       [ 5.29871608,  4.2960304 , -0.29952916,  0.71943733,  1.71372487,
         3.26234829],
       [ 5.28794473,  4.29700451, -0.29889564,  0.70636814,  1.89486817,
         3.2228325 ],
       [ 5.29282246,  4.29189026, -0.29966796,  0.729708  ,  1.74399441,
         3.23007527],
       [ 5.29319911,  4.29088182, -0.2908677 ,  0.73357027,  1.71542858,
         3.23837078],
       [ 4.26456208,  5.29266242, -0.28622185,  0.73662004,  1.81908819,
         2.99493212],
       [ 3.26366692,  5.29312761, -0.2759505 ,  4.28592839,  0.68989672,
         2.17082282],
       [ 5.29343128,  4.29201277,  0.72135168,  0.71437646,  0.71552173,
         3.23766626],
       [ 4.29098434,  5.29870826, -0.28818135,  0.7150296 ,  1.71383841,
         3.24659876],
       [ 1.75373954,  4.11714458,  0.68392819,  3.30320271,  5.31675309,
        -0.29850254],
       [ 0.6874411 ,  2.26249738,  4.2858374 ,  5.29480748,  3.29786087,
        -0.30491048],
       [ 5.28876836,  4.29035817, -0.27818521,  0.70486251,  1.8328914 ,
         3.11694819],
       [ 1.74338936,  4.27203447,  0.77336068,  3.22824992,  4.24949941,
         0.73180663],
       [ 4.26817997,  5.29497423, -0.27768892,  1.74626953,  0.72041242,
         3.20383164],
       [ 4.27819634,  5.29445598, -0.30290652,  0.79184848,  1.75506787,
         3.21296208],
       [ 2.78847554,  5.28337807, -0.27670829,  0.87248351,  4.27282968,
         1.75128667],
       [ 4.26740686,  5.29169502, -0.2987377 ,  1.8128111 ,  0.75583992,
         3.20475404],
       [ 5.28400128,  4.29303951, -0.29508007,  0.73458446,  1.74965927,
         3.20555431],
       [ 5.29071635,  4.29172664, -0.29127181,  0.72230607,  1.73479535,
         3.22130427],
       [ 5.29398235,  4.2928033 , -0.28707692,  0.71663773,  1.71960413,
         3.23750226],
       [ 4.29150571,  5.29167478, -0.28693638,  0.72923089,  1.71388878,
         3.24074857],
       [ 4.29310096,  5.29048915, -0.29275505,  1.73912129,  0.7156048 ,
         3.23973043],
       [ 5.29441759,  4.29413693, -0.30125123,  0.73361818,  1.72318789,
         3.25390263],
       [ 5.28705327,  4.29346135, -0.29697659,  0.74133669,  1.73606957,
         3.21730039],
       [ 0.68154707,  3.30664426,  5.32181336,  4.09285829,  1.70760645,
        -0.30616249],
       [ 5.29498039,  4.29325045, -0.29261698,  0.71898536,  1.72314849,
         3.23677722],
       [ 4.28645489,  5.29507842, -0.28180668,  0.72142397,  1.71704566,
         3.23380287],
       [ 0.73010207,  4.29986962,  5.30636624,  2.76935655,  1.71433906,
        -0.29557856],
       [ 0.68640468,  2.26728275,  4.2899124 ,  5.29269149,  3.29973914,
        -0.30546176],
       [ 4.28512615,  5.2904998 ,  0.73976911,  1.72740589, -0.2904442 ,
         3.22660062],
       [ 5.29041426,  4.29686616, -0.28294036,  0.71281225,  1.71939405,
         3.23085834],
       [ 5.28965036,  4.29541325, -0.31064781,  0.72905078,  2.16768966,
         3.24082782],
       [ 5.29763993,  4.29132821, -0.29280861,  0.71397767,  1.72675905,
         3.23926946],
       [ 0.69216762,  4.29125894,  5.29810113,  1.82968273,  3.29517139,
        -0.30303588],
       [ 1.68272819,  3.31703446,  5.32015546,  4.30922483, -0.32097863,
         0.69482266],
       [ 4.26477382,  5.29240654, -0.26427358,  0.73510415,  1.7379362 ,
         3.08964422],
       [ 4.2925974 ,  5.29582826, -0.29754547,  0.73010339,  1.71613537,
         3.25465237],
       [ 5.29180142,  4.29762947, -0.29660628,  0.70475371,  1.7756619 ,
         3.23874573],
       [ 5.29723587,  4.29135176, -0.29158586,  0.71630548,  1.72095632,
         3.24239144],
       [ 5.29638701,  4.29639021, -0.31159173,  0.7185918 ,  2.16004919,
         3.24520789],
       [ 0.68994896,  2.24979913,  3.24367142,  5.30488817,  4.29287632,
        -0.30396132],
       [ 4.2748671 ,  5.29226606, -0.29113097,  1.7816967 ,  0.72520592,
         3.2086002 ],
       [ 4.2801946 ,  5.29185299,  0.7306698 ,  1.74427152, -0.29086917,
         3.22383825],
       [ 4.28265523,  5.29732465, -0.30055029,  1.76358738,  0.72112705,
         3.24771539],
       [ 4.28764442,  5.29069361, -0.29630789,  0.74248484,  1.73409336,
         3.23012748],
       [ 0.68929805,  2.2576679 ,  3.2569578 ,  5.29539432,  4.30216984,
        -0.30440633],
       [ 4.2274647 ,  5.2956896 ,  2.09029015,  0.72084324, -0.27707456,
         2.92361469],
       [ 4.28695215,  5.29320066, -0.28814528,  1.73940854,  0.71612966,
         3.22934324],
       [ 5.29021664,  4.28919952, -0.30482693,  0.77969046,  1.75238782,
         3.23068526],
       [ 5.29690352,  4.29027474, -0.30008376,  0.7304388 ,  1.72867847,
         3.24411257],
       [ 1.80284909,  5.29677465,  4.30165523, -0.30450212,  2.77214805,
         0.74122251],
       [ 1.77718035,  5.2977645 ,  4.29281301, -0.29961775,  2.80063484,
         0.74590291],
       [ 0.68892774,  2.2580582 ,  3.24694568,  5.2978209 ,  4.30262342,
        -0.30448229],
       [ 0.68882817,  3.28237559,  4.28272442,  3.23048401,  4.3061752 ,
        -0.30460142],
       [ 5.29917077,  4.29442418, -0.30413915,  0.72989199,  1.71965118,
         3.26175436],
       [ 5.29326491,  4.29406303, -0.29729759,  0.73156015,  1.71990088,
         3.24655161],
       [ 0.6880017 ,  2.25995646,  4.2888519 ,  5.28987386,  3.29828651,
        -0.30458241],
       [ 4.28887345,  5.29434009, -0.28153241,  1.72690991,  0.70997391,
         3.2412287 ],
       [ 5.29291974,  4.29614482, -0.29307862,  0.7201486 ,  1.72047014,
         3.23801992],
       [ 5.2920919 ,  4.29838192, -0.30360088,  0.71296595,  1.77274269,
         3.24859105],
       [ 0.70323404,  5.29776844,  2.18034718,  2.94249506,  4.27604647,
        -0.28602503]])

In [14]:
svm.predict(x_test)

array(['building_windows_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_non_float_processed', 'tableware', 'headlamps',
       'building_windows_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed', 'containers',
       'building_windows_float_processed',
       'building_windows_non_float_processed', 'containers', 'headlamps',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed', 'containers', 'containers',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed', 'headlamps',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed', 'headlamps',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_non_float_processed',
       'building_windows_non_float_processed', 'headlamps', 'containers',
       'building_windows_float_processed',
       'building_windows_float_processed', 'headlamps',
       'building_windows_non_float_processed',
       'building_windows_float_processed',
       'building_windows_float_processed',
       'building_windows_non_float_processed'], dtype=object)

In [15]:
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for g in Gs:
        for d in dfs:
            svm=SVC(kernel='rbf',C=c,gamma=g,decision_function_shape=d)
            svm.fit(x_train,y_train)
            y_pred=svm.predict(x_test)
        scores.append([c,g,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Gamma','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

            C     Gamma Decision Function Shape  Accuracy
361  4.736895  0.264105                     ovr  0.723077
381  5.000000  0.264105                     ovr  0.723077
301  3.947579  0.264105                     ovr  0.723077
321  4.210684  0.264105                     ovr  0.723077
281  3.684474  0.264105                     ovr  0.723077
..        ...       ...                     ...       ...
4    0.001000  1.053421                     ovr  0.353846
1    0.001000  0.264105                     ovr  0.353846
2    0.001000  0.527211                     ovr  0.353846
3    0.001000  0.790316                     ovr  0.353846
0    0.001000  0.001000                     ovr  0.353846

[400 rows x 4 columns]

In [16]:
Cs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for d in dfs:
        svm=SVC(kernel='rbf',C=c,gamma=0.2,decision_function_shape=d)
        svm.fit(x_train,y_train)
        y_pred=svm.predict(x_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

           C Decision Function Shape  Accuracy
39  5.000000                     ovr  0.723077
38  5.000000                     ovo  0.723077
10  1.316526                     ovo  0.707692
11  1.316526                     ovr  0.707692
6   0.790316                     ovo  0.692308
7   0.790316                     ovr  0.692308
13  1.579632                     ovr  0.692308
12  1.579632                     ovo  0.692308
23  2.895158                     ovr  0.692308
22  2.895158                     ovo  0.692308
24  3.158263                     ovo  0.692308
25  3.158263                     ovr  0.692308
28  3.684474                     ovo  0.692308
29  3.684474                     ovr  0.692308
9   1.053421                     ovr  0.692308
8   1.053421                     ovo  0.692308
16  2.105842                     ovo  0.692308
17  2.105842                     ovr  0.692308
18  2.368947                     ovo  0.692308
19  2.368947                     ovr  0.692308
20  2.632053                     ovo  0.692308
21  2.632053                     ovr  0.692308
14  1.842737                     ovo  0.692308
15  1.842737                     ovr  0.692308
31  3.947579                     ovr  0.692308
30  3.947579                     ovo  0.692308
32  4.210684                     ovo  0.692308
33  4.210684                     ovr  0.692308
35  4.473789                     ovr  0.692308
34  4.473789                     ovo  0.692308
26  3.421368                     ovo  0.692308
27  3.421368                     ovr  0.692308
37  4.736895                     ovr  0.692308
36  4.736895                     ovo  0.692308
5   0.527211                     ovr  0.630769
4   0.527211                     ovo  0.630769
3   0.264105                     ovr  0.584615
2   0.264105                     ovo  0.584615
1   0.001000                     ovr  0.353846
0   0.001000                     ovo  0.353846

In [17]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for d in dfs:
        svm=SVC(kernel='rbf',C=c,gamma=0.2,decision_function_shape=d)
        svm.fit(x_train,y_train)
        y_pred=svm.predict(x_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

           C Decision Function Shape  Accuracy
0   0.001000                     ovo  0.353846
1   0.001000                     ovr  0.353846
2   0.264105                     ovo  0.353846
3   0.264105                     ovr  0.353846
4   0.527211                     ovo  0.353846
5   0.527211                     ovr  0.353846
6   0.790316                     ovo  0.353846
7   0.790316                     ovr  0.353846
8   1.053421                     ovo  0.353846
9   1.053421                     ovr  0.353846
10  1.316526                     ovo  0.353846
11  1.316526                     ovr  0.353846
12  1.579632                     ovo  0.353846
13  1.579632                     ovr  0.353846
14  1.842737                     ovo  0.353846
15  1.842737                     ovr  0.353846
16  2.105842                     ovo  0.353846
17  2.105842                     ovr  0.353846
18  2.368947                     ovo  0.353846
19  2.368947                     ovr  0.353846
20  2.632053                     ovo  0.353846
21  2.632053                     ovr  0.353846
22  2.895158                     ovo  0.353846
23  2.895158                     ovr  0.353846
24  3.158263                     ovo  0.353846
25  3.158263                     ovr  0.353846
26  3.421368                     ovo  0.353846
27  3.421368                     ovr  0.353846
28  3.684474                     ovo  0.353846
29  3.684474                     ovr  0.353846
30  3.947579                     ovo  0.353846
31  3.947579                     ovr  0.353846
32  4.210684                     ovo  0.353846
33  4.210684                     ovr  0.353846
34  4.473789                     ovo  0.353846
35  4.473789                     ovr  0.353846
36  4.736895                     ovo  0.353846
37  4.736895                     ovr  0.353846
38  5.000000                     ovo  0.353846
39  5.000000                     ovr  0.353846

In [18]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for g in Gs:
        for d in dfs:
            svm=SVC(kernel='rbf',C=c,gamma=g,decision_function_shape=d)
            svm.fit(x_train,y_train)
            y_pred=svm.predict(x_test)
        scores.append([c,g,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Gamma','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

         C     Gamma Decision Function Shape  Accuracy
0    0.001  0.001000                     ovr  0.353846
1    0.001  0.264105                     ovr  0.353846
2    0.001  0.527211                     ovr  0.353846
3    0.001  0.790316                     ovr  0.353846
4    0.001  1.053421                     ovr  0.353846
..     ...       ...                     ...       ...
395  5.000  3.947579                     ovr  0.353846
396  5.000  4.210684                     ovr  0.353846
397  5.000  4.473789                     ovr  0.353846
398  5.000  4.736895                     ovr  0.353846
399  5.000  5.000000                     ovr  0.353846

[400 rows x 4 columns]

In [19]:
mm=MinMaxScaler()
x_train=mm.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for d in dfs:
        svm=SVC(kernel='rbf',C=c,gamma=0.2,decision_function_shape=d)
        svm.fit(x_train,y_train)
        y_pred=svm.predict(x_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

           C Decision Function Shape  Accuracy
0   0.001000                     ovo  0.353846
1   0.001000                     ovr  0.353846
2   0.264105                     ovo  0.353846
3   0.264105                     ovr  0.353846
4   0.527211                     ovo  0.353846
5   0.527211                     ovr  0.353846
6   0.790316                     ovo  0.353846
7   0.790316                     ovr  0.353846
8   1.053421                     ovo  0.353846
9   1.053421                     ovr  0.353846
10  1.316526                     ovo  0.353846
11  1.316526                     ovr  0.353846
12  1.579632                     ovo  0.353846
13  1.579632                     ovr  0.353846
14  1.842737                     ovo  0.353846
15  1.842737                     ovr  0.353846
16  2.105842                     ovo  0.353846
17  2.105842                     ovr  0.353846
18  2.368947                     ovo  0.353846
19  2.368947                     ovr  0.353846
20  2.632053                     ovo  0.353846
21  2.632053                     ovr  0.353846
22  2.895158                     ovo  0.353846
23  2.895158                     ovr  0.353846
24  3.158263                     ovo  0.353846
25  3.158263                     ovr  0.353846
26  3.421368                     ovo  0.353846
27  3.421368                     ovr  0.353846
28  3.684474                     ovo  0.353846
29  3.684474                     ovr  0.353846
30  3.947579                     ovo  0.353846
31  3.947579                     ovr  0.353846
32  4.210684                     ovo  0.353846
33  4.210684                     ovr  0.353846
34  4.473789                     ovo  0.353846
35  4.473789                     ovr  0.353846
36  4.736895                     ovo  0.353846
37  4.736895                     ovr  0.353846
38  5.000000                     ovo  0.353846
39  5.000000                     ovr  0.353846

In [20]:
mm=MinMaxScaler()
x_train=mm.fit_transform(x_train)
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for g in Gs:
        for d in dfs:
            svm=SVC(kernel='rbf',C=c,gamma=g,decision_function_shape=d)
            svm.fit(x_train,y_train)
            y_pred=svm.predict(x_test)
        scores.append([c,g,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Gamma','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

         C     Gamma Decision Function Shape  Accuracy
0    0.001  0.001000                     ovr  0.353846
1    0.001  0.264105                     ovr  0.353846
2    0.001  0.527211                     ovr  0.353846
3    0.001  0.790316                     ovr  0.353846
4    0.001  1.053421                     ovr  0.353846
..     ...       ...                     ...       ...
395  5.000  3.947579                     ovr  0.353846
396  5.000  4.210684                     ovr  0.353846
397  5.000  4.473789                     ovr  0.353846
398  5.000  4.736895                     ovr  0.353846
399  5.000  5.000000                     ovr  0.353846

[400 rows x 4 columns]

In [21]:
Cs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for d in dfs:
        svm=SVC(kernel='linear',C=c,gamma=0.2,decision_function_shape=d)
        svm.fit(x_train,y_train)
        y_pred=svm.predict(x_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

           C Decision Function Shape  Accuracy
0   0.001000                     ovo  0.353846
1   0.001000                     ovr  0.353846
2   0.264105                     ovo  0.046154
3   0.264105                     ovr  0.046154
4   0.527211                     ovo  0.046154
5   0.527211                     ovr  0.046154
6   0.790316                     ovo  0.046154
7   0.790316                     ovr  0.046154
8   1.053421                     ovo  0.046154
9   1.053421                     ovr  0.046154
10  1.316526                     ovo  0.046154
11  1.316526                     ovr  0.046154
12  1.579632                     ovo  0.046154
13  1.579632                     ovr  0.046154
14  1.842737                     ovo  0.046154
15  1.842737                     ovr  0.046154
16  2.105842                     ovo  0.046154
17  2.105842                     ovr  0.046154
18  2.368947                     ovo  0.046154
19  2.368947                     ovr  0.046154
20  2.632053                     ovo  0.046154
21  2.632053                     ovr  0.046154
22  2.895158                     ovo  0.046154
23  2.895158                     ovr  0.046154
24  3.158263                     ovo  0.046154
25  3.158263                     ovr  0.046154
26  3.421368                     ovo  0.046154
27  3.421368                     ovr  0.046154
28  3.684474                     ovo  0.046154
29  3.684474                     ovr  0.046154
30  3.947579                     ovo  0.046154
31  3.947579                     ovr  0.046154
32  4.210684                     ovo  0.046154
33  4.210684                     ovr  0.046154
34  4.473789                     ovo  0.046154
35  4.473789                     ovr  0.046154
36  4.736895                     ovo  0.046154
37  4.736895                     ovr  0.046154
38  5.000000                     ovo  0.046154
39  5.000000                     ovr  0.046154

## TQDM

In [25]:
from tqdm import tqdm
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in tqdm(Cs):
    for g in Gs:
        for d in dfs:
            svm=SVC(kernel='rbf',C=c,gamma=g,decision_function_shape=d)
            svm.fit(x_train,y_train)
            y_pred=svm.predict(x_test)
        scores.append([c,g,d,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','Gamma','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [00:04<00:00,  4.35it/s]

            C     Gamma Decision Function Shape  Accuracy
361  4.736895  0.264105                     ovr  0.723077
381  5.000000  0.264105                     ovr  0.723077
301  3.947579  0.264105                     ovr  0.723077
321  4.210684  0.264105                     ovr  0.723077
281  3.684474  0.264105                     ovr  0.723077
..        ...       ...                     ...       ...
4    0.001000  1.053421                     ovr  0.353846
1    0.001000  0.264105                     ovr  0.353846
2    0.001000  0.527211                     ovr  0.353846
3    0.001000  0.790316                     ovr  0.353846
0    0.001000  0.001000                     ovr  0.353846

[400 rows x 4 columns]

In [46]:
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder
car_evaluation = fetch_ucirepo(id=19)
x = car_evaluation.data.features
y = car_evaluation.data.targets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25, stratify=y)

In [47]:
x

     buying  maint  doors persons lug_boot safety
0     vhigh  vhigh      2       2    small    low
1     vhigh  vhigh      2       2    small    med
2     vhigh  vhigh      2       2    small   high
3     vhigh  vhigh      2       2      med    low
4     vhigh  vhigh      2       2      med    med
...     ...    ...    ...     ...      ...    ...
1723    low    low  5more    more      med    med
1724    low    low  5more    more      med   high
1725    low    low  5more    more      big    low
1726    low    low  5more    more      big    med
1727    low    low  5more    more      big   high

[1728 rows x 6 columns]

In [48]:
le=LabelEncoder()
y=le.fit_transform(y['class'])
le.classes_

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [50]:
from sklearn.pipeline import Pipeline
ohe=OneHotEncoder(drop='first')
Cs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for d in dfs:
        svm=SVC(kernel='linear',C=c,decision_function_shape=d)
        pipe=Pipeline([('OHE',ohe),('SVM',svm)])
        pipe.fit(x_train,y_train)
        y_pred=pipe.predict(x_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])

df_scores=pd.DataFrame(scores,columns=['C','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

           C Decision Function Shape  Accuracy
30  3.947579                     ovo  0.932563
31  3.947579                     ovr  0.932563
21  2.632053                     ovr  0.932563
20  2.632053                     ovo  0.932563
36  4.736895                     ovo  0.928709
37  4.736895                     ovr  0.928709
39  5.000000                     ovr  0.928709
38  5.000000                     ovo  0.928709
35  4.473789                     ovr  0.928709
34  4.473789                     ovo  0.928709
27  3.421368                     ovr  0.926782
26  3.421368                     ovo  0.926782
33  4.210684                     ovr  0.926782
32  4.210684                     ovo  0.926782
22  2.895158                     ovo  0.924855
23  2.895158                     ovr  0.924855
28  3.684474                     ovo  0.924855
29  3.684474                     ovr  0.924855
25  3.158263                     ovr  0.924855
24  3.158263                     ovo  0.924855
19  2.368947                     ovr  0.922929
18  2.368947                     ovo  0.922929
17  2.105842                     ovr  0.922929
16  2.105842                     ovo  0.922929
14  1.842737                     ovo  0.919075
15  1.842737                     ovr  0.919075
12  1.579632                     ovo  0.917148
13  1.579632                     ovr  0.917148
10  1.316526                     ovo  0.915222
11  1.316526                     ovr  0.915222
8   1.053421                     ovo  0.909441
9   1.053421                     ovr  0.909441
7   0.790316                     ovr  0.897881
6   0.790316                     ovo  0.897881
5   0.527211                     ovr  0.890173
4   0.527211                     ovo  0.890173
3   0.264105                     ovr  0.888247
2   0.264105                     ovo  0.888247
1   0.001000                     ovr  0.699422
0   0.001000                     ovo  0.699422

In [51]:
from sklearn.pipeline import Pipeline
ohe=OneHotEncoder(drop='first')
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
dfs=['ovo','ovr']
scores=[]
for c in Cs:
    for g in Gs:
        for d in dfs:
            svm=SVC(kernel='linear',C=c,gamma=g,decision_function_shape=d)
            pipe=Pipeline([('OHE',ohe),('SVM',svm)])
            pipe.fit(x_train,y_train)
            y_pred=pipe.predict(x_test)
            scores.append([c,g,d,accuracy_score(y_test,y_pred)])

df_scores=pd.DataFrame(scores,columns=['C','Gamma','Decision Function Shape','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

            C     Gamma Decision Function Shape  Accuracy
400  2.632053  0.001000                     ovo  0.932563
401  2.632053  0.001000                     ovr  0.932563
402  2.632053  0.264105                     ovo  0.932563
403  2.632053  0.264105                     ovr  0.932563
404  2.632053  0.527211                     ovo  0.932563
..        ...       ...                     ...       ...
20   0.001000  2.632053                     ovo  0.699422
19   0.001000  2.368947                     ovr  0.699422
18   0.001000  2.368947                     ovo  0.699422
17   0.001000  2.105842                     ovr  0.699422
16   0.001000  2.105842                     ovo  0.699422

[800 rows x 4 columns]